apiVersion: apps/v1
kind: Deployment
metadata:
  name: dosnowly
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dosnowly
  template:
    metadata:
      labels:
        app: dosnowly
    spec:
      containers:
      - image: okteto.dev/dosnowly:latest
        name: dosnowly
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "23b94eb1-c4f7-4d7c-a93a-de9d0ac6ede5"
        - name: Vless_Path
          value: "/vlbeauty22"
        - name: Vmess_UUID
          value: "23b94eb1-c4f7-4d7c-a93a-de9d0ac6ede5"
        - name: Vmess_Path
          value: "/vmbeauty23"
        - name: Share_Path
          value: "/v2link"
